package com.usercrud.api.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity mapped to the {@code users} table.
 *
 * <p>Represents a user record with system-assigned id, name, email, and optional role.
 * Satisfies FR-005, FR-013, CONTRACT-DB-01.
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * System-assigned primary key; BIGINT GENERATED BY DEFAULT AS IDENTITY.
     * Satisfies FR-005, FR-013, CONTRACT-DB-01.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Required user name; max 100 characters; NOT NULL.
     * Satisfies BC-001, CONTRACT-DB-01.
     */
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * Required unique email address; max 150 characters; NOT NULL; UNIQUE.
     * Satisfies BC-002, CONTRACT-DB-01.
     */
    @Column(nullable = false, unique = true, length = 150)
    private String email;

    /**
     * Optional role; max 20 characters; nullable.
     * Permitted values: USER, ADMIN, GUEST (CONTRACT-DB-03).
     * Satisfies BC-003, CONTRACT-DB-01.
     */
    @Column(length = 20)
    private String role;

    /** Default no-arg constructor required by JPA. */
    public User() {
    }

    /**
     * Full constructor for entity creation.
     *
     * @param id    the user id
     * @param name  the user name
     * @param email the user email
     * @param role  the user role
     */
    public User(final Long id, final String name, final String email, final String role) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.role = role;
    }

    public Long getId() { return id; }
    public void setId(final Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(final String name) { this.name = name; }

    public String getEmail() { return email; }
    public void setEmail(final String email) { this.email = email; }

    public String getRole() { return role; }
    public void setRole(final String role) { this.role = role; }
}
