-- Flyway migration V1: create users table
-- Satisfies CONTRACT-DB-01

CREATE TABLE users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(100)  NOT NULL,
    email VARCHAR(150)  NOT NULL,
    role  VARCHAR(20),
    CONSTRAINT uq_users_email UNIQUE (email)
);
